project_id = "zwpkxypaomlygugdnhsk"

[functions.get-order]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.motoboy-deliver]
verify_jwt = false